apiVersion: v1
kind: ConfigMap
metadata:
  name: foo
  namespace: default
data:
  value1: Foo1
  value2: Foo2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bar
  namespace: default
data:
  value1: Bar1
  value2: Bar2