apiVersion: krateo.io/v1alpha1
kind: Patch
metadata:
  name: sample-1
spec:
  from:
    objectReference:
      apiVersion: v1
      kind: ConfigMap
      namespace: default
      name: foo
    fieldPath: data.value
  to:
    objectReference:
      apiVersion: v1
      kind: ConfigMap
      namespace: default
      name: bar
    fieldPath: data.value
