apiVersion: krateo.io/v1alpha1
kind: Patch
metadata:
  name: sample1
spec:
  from:
    objectReference:
      apiVersion: v1
      kind: ConfigMap
      name: foo
      # namespace: default
    fieldPath: data.value
  to:
    objectReference:
      apiVersion: v1
      kind: ConfigMap
      name: bar
      # namespace: default
    fieldPath: data.value
    transform: b64enc
